### ISSUE TITLE
[Bug]: Parameter $volume of class Kiwilan\Opds\Entries\OpdsEntryBook constructor expects int|null, float|null give

### ISSUE THREAD

**Issue by mikespub** [kiwilan/php-opds#36]
### What happened?

I might as well post this one too while I'm reporting issues :-)

As the title says, OpdsEntryBook expects 'volume' to be `int`, but Calibre actually uses `float` to cover series indexes like 1.25

And the OPDS 2.0 draft states that the 'position' it is converted to can be either an integer or a float:
https://github.com/readium/webpub-manifest/tree/master/contexts/default
which translates to type 'number' in json schema:
https://json-schema.org/understanding-json-schema/reference/numeric.html#number

### How to reproduce the bug

Try to use calibre series_index for volume

### Package Version

1.0.23

### PHP Version

8.2

### Which operating systems does with happen with?

Linux

**Comment by ewilan-riviere** [comment]
Tell me if it's okay with `v1.0.30` ;)

**Comment by mikespub** [comment]
Thanks, works for me
